server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dashboard?&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: dyh18215153215
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true